
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/electricity
      SPRING_DATASOURCE_USERNAME: academy
      SPRING_DATASOURCE_PASSWORD: academy
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: my_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: